# Generated by Django 5.0.2 on 2024-02-18 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('service', models.CharField(choices=[('VR', 'Vocal-Recording'), ('MM', 'Mix-Master'), ('FSB', 'Full-Song-Beat'), ('FSOB', 'Full-Song-Own-Beat'), ('AMCD', 'Album-music-cover-design'), ('BP', 'Beat-Production'), ('MVE', 'Music-Video-Recording')], max_length=4)),
                ('date', models.DateField(max_length=10)),
                ('number_of_hours', models.IntegerField()),
                ('genre', models.CharField(choices=[('C', 'Classical'), ('HH', 'Hip-Hop'), ('J', 'Jazz'), ('F', 'Funck'), ('R', 'R-N-B'), ('P', 'Pop'), ('RK', 'Rock'), ('M', 'Metal')], max_length=2)),
                ('phone_number', models.CharField(max_length=10)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
